/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * helpFRM.java
 *
 * Created on 14 Dec, 2015, 2:24:00 AM
 */

/**
 *
 * @author Comp11
 */
public class helpFRM extends javax.swing.JFrame {

    /** Creates new form helpFRM */
    public helpFRM() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        repTA = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Help");

        panel1.setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setBackground(new java.awt.Color(0, 204, 255));
        jLabel1.setFont(new java.awt.Font("Algerian", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Help Menu");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(605, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        hList.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        hList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "About the Program", "<html>Hardware and<br> Software Requirements", "Depreciation Value", "<html>E-Waste Disposal<br>and its Management", "About KVS", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        hList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        hList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                hListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(hList);

        repTA.setEditable(false);
        repTA.setColumns(20);
        repTA.setFont(new java.awt.Font("Bodoni MT", 1, 24)); // NOI18N
        repTA.setRows(5);
        jScrollPane2.setViewportView(repTA);

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 51));
        jLabel2.setText("Help Contents-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_hListValueChanged
 int i=hList.getSelectedIndex();
        switch(i){
            case 0:
                repTA.setText("");
                repTA.append('\t'+"About the Program"+'\n');
                repTA.append("The program is designed to facilitate the management of" +'\n');
                repTA.append("Physics lab equipments and materials more systematically"+'\n');
                repTA.append("and more acccuerately. The application can perform basic "+'\n');
                repTA.append("functions:-"+'\n');
                repTA.append("1.Add an Item"+'\n');
                repTA.append("2.Remove an Item"+'\n');
                repTA.append("3.Update Item Details"+'\n');
                repTA.append("4.Show Item Details"+'\n');
                repTA.append("5.Issuing an Item"+'\n');
                repTA.append("6.Calculate Depreciation Value,and"+'\n');
                repTA.append("7.Search in the Database as per defined criterion."+'\n'+'\n');
                repTA.append('\t'+"Objective and Scope of Project"+'\n');
                repTA.append("The objective of the proposed system would be to overcome " +'\n');
                repTA.append("the problems faced in the manual system. Updating records"+'\n');
                repTA.append("would not be a problem and also cross checking of a records "+'\n');
                repTA.append("in the proposed system would not be required."+'\n');
                repTA.append("Mathematical, accounting and logical errors would get automatically " +'\n');
                repTA.append("rectified in the proposed system.Report can be generated on  "+'\n');
                repTA.append("the click of a button.This, system play’s a vital role in having a "+'\n');
                repTA.append("systematic and easy to work with area. In that project the entire thing"+'\n');
                repTA.append("are first, given a unique number that must not be duplicated and" +'\n');
                repTA.append("then they are arranged in a proper sequenced order. So that it "+'\n');
                repTA.append("becomes easy to keep track all the things and information about"+'\n');
                repTA.append("them."+'\n');
                break;
            case 1:
                 repTA.setText("");
                repTA.append("HARDWARE Specification of machine used:"+'\n');
                repTA.append('\t'+"Processor :                                Intel"+'\n');
                repTA.append('\t'+"Memory[RAM] :                         16 MB"+'\n');
                repTA.append('\t'+"Hard Disk Drive :                           1.5 GB"+'\n');
                repTA.append('\t'+"Display Type :                              Digital monitor"+'\n');
                repTA.append('\t'+"Keyboard :                                   Multimedia"+'\n');
                repTA.append('\t'+"Control :                                      ASCII"+'\n');
                repTA.append('\t'+"Printer :                                        Ink Jet"+'\n'+'\n');
                repTA.append("CD ROM DRIVE:"+'\n'+"48x or 52x higher (to installation)"+'\n'+"Software (o.s, languages, packages)."+'\n');
                repTA.append("Operating System:"+'\n'+"Windows XP or Higher Version."+'\n');
                repTA.append("Languages:"+'\n'+"Java (front end) & My Sql (Back end)."+'\n');
                break;
            case 2:
                repTA.setText("");
                 repTA.append(""+'\t'+"Depreciation Value"+'\n');
                repTA.append('\n'+"Depreciation value is the reduced value of an asset over time, "+'\n');
                repTA.append("due to in perticular to wear and tear."+'\n');
                repTA.append("Depreciation Formula Used  is:-"+'\n');
                repTA.append("Price at Purchase-(Depreciation per 100 days*no. of days)"+'\n');

                break;
            case 3:
                 repTA.setText("");
                repTA.append(""+'\t'+"E-Waste and Its Disposal"+'\n');
                repTA.append('\n'+"Electronic scrap components, such as CRTs, may contain contaminants"+'\n');
                repTA.append("such as lead,cadmium, beryllium, or brominated flame retardants. Even in"+'\n');
                repTA.append("developed countries recycling and disposal of e-waste may involve significant"+'\n');
                repTA.append("risk to workers and communities and great care must be taken to avoid unsafe"+'\n');
                repTA.append("exposure in recycling operations and leaking of materials such as heavy metals"+'\n');
                repTA.append("from landfills and incinerator ashes."+'\n');
                repTA.append("The processes of dismantling and disposing of electronic waste in the third world"+'\n');
                repTA.append("lead to a number of environmental impacts. Liquid and atmospheric releases end"+'\n');
                repTA.append("up in bodies of water, groundwater, soil, and air and therefore in land and sea"+'\n');
                repTA.append("animals – both domesticated and wild, in crops eaten by both animals and human,"+'\n');
                repTA.append("and in drinking water"+'\n'+'\n');
                repTA.append(""+'\t'+"E-Waste Management"+'\n');
                repTA.append("Audiovisual components, televisions, VCRs, stereo equipment, mobile phones,"+'\n');
                repTA.append("other handheld devices, and computer components contain valuable elements and"+'\n');
                repTA.append("substances suitable for reclamation, including lead, copper, and gold.One of the"+'\n');
                repTA.append("major challenges is recycling the printed circuit boards from the electronic wastes."+'\n');
                repTA.append("The circuit boards contain such precious metals as gold, silver, platinum, etc. and"+'\n');
                repTA.append("such base metals as copper, iron, aluminum, etc. One way e-waste is processed is"+'\n');
                repTA.append("by melting circuit boards, burning cable sheathing to recover copper wire"+'\n');
                repTA.append("and open- pit acid leaching for separating metals of value. Conventional method"+'\n');
                repTA.append("employed is mechanical shredding and separation but the recycling efficiency is"+'\n');
                repTA.append("low. Alternative methods such as cryogenic decomposition have been studied for"+'\n');
                repTA.append("printed circuit board recycling, and some other methods are still under investigation."+'\n');
                break;
            case 4:
                 repTA.setText("");
                repTA.append('\t'+"Kendriya Vidyalaya Sangathan(K.V.S)"+'\n'+'\n');
                repTA.append("The Kendriya Vidyalayas are a system of central government schools in India that have"+'\n');
repTA.append("been instituted under the aegis of the Ministry of Human Resource Development"+'\n');
repTA.append("(MHRD). It comprises over a thousand schools in India and three abroad. The system"+'\n');
repTA.append("came into being in 1963 under the name 'Central Schools'. Later, the name was "+'\n');
repTA.append("changed to Kendriya Vidyalaya. All the schools are affiliated to the Central Board of "+'\n');
repTA.append("Secondary Education (CBSE).Its objective is to educate children of the Indian Defence"+'\n');
repTA.append("Services personnel who are often posted to remote locations. With the army starting its"+'\n');
repTA.append("own Army Public Schools, the service was extended (but not restricted) to all central"+'\n');
repTA.append("government employees."+'\n'+'\n');
repTA.append("A uniform curriculum is followed by these schools all over India. By providing a common"+'\n');
repTA.append("syllabus and system of education, the Kendriya Vidyalayas are intended to ensure that"+'\n');
repTA.append("the children of government employees do not face education disadvantages while their"+'\n');
repTA.append("parents are transferred from one location to another. The schools have been operational"+'\n');
repTA.append("for over fifty years."+'\n');

repTA.append("The Kendriya Vidyalaya Sangathan, which literally translates to 'Central School"+'\n');
repTA.append("Organisation', oversees the functioning of these schools and has its headquarters in"+'\n');
repTA.append("New Delhi. The administration of this body is based on levels; the chairman of Kendriya"+'\n');
repTA.append("Vidyalaya Sangathan is always the Minister of Human Resource Development of the Govt. "+'\n');
repTA.append("Working power lies with the Commissioner of KVS; there are additional commissioners"+'\n');
repTA.append("to accompany Commissioner in the administration of KVS in different fields. The head of"+'\n');
repTA.append("a KVS region is Deputy Commissioner accompanied by an Assistant Commissioner."+'\n');
repTA.append("There are individual principals of every KV administering the school they are in charge"+'\n');
repTA.append("of."+'\n'+'\n');
break;
        }// TODO add your handling code here:
}//GEN-LAST:event_hListValueChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new helpFRM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList hList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Panel panel1;
    private javax.swing.JTextArea repTA;
    // End of variables declaration//GEN-END:variables

}
