import java.sql.*;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * issueFRM.java
 *
 * Created on 13 Dec, 2015, 4:23:53 PM
 */

/**
 *
 * @author Comp11
 */
public class issueFRM extends javax.swing.JFrame {

    /** Creates new form issueFRM */
    public issueFRM() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Btn1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        itemCB = new javax.swing.JComboBox();
        qtyTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panel1.setBackground(new java.awt.Color(0, 255, 0));

        jLabel1.setBackground(new java.awt.Color(0, 204, 255));
        jLabel1.setFont(new java.awt.Font("Aharoni", 3, 36));
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Issue a Item from Physics Lab");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images (6).jpg"))); // NOI18N
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jLabel4.setText("Name of Item");

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jLabel5.setText("Qty Required");

        Btn1.setFont(new java.awt.Font("Bookman Old Style", 3, 24)); // NOI18N
        Btn1.setText("Issue");
        Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Bookman Old Style", 3, 24));
        jButton2.setText("<html>Back To<br>Main Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        itemCB.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        itemCB.setEnabled(false);
        itemCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCBActionPerformed(evt);
            }
        });
        itemCB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                itemCBFocusGained(evt);
            }
        });

        qtyTF.setEditable(false);
        qtyTF.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        qtyTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyTFActionPerformed(evt);
            }
        });
        qtyTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                qtyTFFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(285, 285, 285)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qtyTF, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                            .addComponent(itemCB, 0, 277, Short.MAX_VALUE))
                        .addGap(142, 142, 142))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(itemCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(qtyTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel5))))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(Btn1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1ActionPerformed
String str1 = (String)itemCB.getSelectedItem();
String str2=qtyTF.getText();
if(str2.length()==0){
JOptionPane.showMessageDialog(null,"Please write no. of Item issued!");
}
else if(!str2.matches("[0-9]*")){
JOptionPane.showMessageDialog(null,"Please type only numbers in Qty. field");
}
else if(str2.length()!=0){
try{
                Class.forName("com.mysql.jdbc.Driver");
                System.out.print("\nConnecting to database...");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/kashyap", "root", "kvalwar");
System.out.println(" SUCCESS!\n");
Statement stmt = con.createStatement();
int p=Integer.parseInt(str2);
String query = "SELECT * FROM lab WHERE ItemName="+"'"+str1+"';";
ResultSet rs = stmt.executeQuery(query);
int ty=0;
if ( rs.next()){
String price = rs.getString(3);
String life = rs.getString(4);
String  qty= rs.getString(5);
String dep = rs.getString(6);
String  date = rs.getString(7);
ty=Integer.parseInt(qty);
if(ty<p){
JOptionPane.showMessageDialog(null,"Sorry, insufficent stock");
}
else{
    String query1="UPDATE lab SET number=number-"+str2+" "+"WHERE ItemName= "+"'"+str1+"';";
stmt.executeUpdate(query1);
DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
Date date2 = new Date();
JOptionPane.showMessageDialog(null,"<html><b><u>Report</u></b><br><br>Item Issued Successfully.<br>Date:-"+date2);
}
}
rs.close();
stmt.close();
con.close();
}
catch(Exception e){
    JOptionPane.showMessageDialog(null,"Error in Connectivity!");
}
}// TODO add your handling code here:
}//GEN-LAST:event_Btn1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  myFrame2 frame=new myFrame2();
            issueFRM.this.setVisible(false);
            frame.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void itemCBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemCBFocusGained
        // TODO add your handling code here:
}//GEN-LAST:event_itemCBFocusGained

    private void itemCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCBActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_itemCBActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
try {
Class.forName("com.mysql.jdbc.Driver");
System.out.print("\nConnecting to database...");
Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/kashyap", "root", "kvalwar");
System.out.println(" SUCCESS!\n");
Statement statement = connection.createStatement();
String query = "SELECT * FROM lab";
ResultSet rs = statement.executeQuery(query);
while (rs.next())
{
String name = rs.getString("ItemName");
itemCB.addItem(name);
}
connection.close();
itemCB.setEnabled(true);
qtyTF.setEditable(true);
Btn1.setEnabled(true);
}
catch (Exception e) {
e.printStackTrace();
}        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void qtyTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qtyTFFocusLost
String a=qtyTF.getText();
if(!jButton2.getModel().isPressed()){
 if(!a.matches("[0-9]*")){
     JOptionPane.showMessageDialog(null,"Please type only numbers in qty. issued Field");
     qtyTF.setText("");
    }}        // TODO add your handling code here:
    }//GEN-LAST:event_qtyTFFocusLost

    private void qtyTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyTFActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new issueFRM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn1;
    private javax.swing.JComboBox itemCB;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private java.awt.Panel panel1;
    private javax.swing.JTextField qtyTF;
    // End of variables declaration//GEN-END:variables

}
