import java.sql.*;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * returnFRM.java
 *
 * Created on 13 Dec, 2015, 5:54:38 PM
 */

/**
 *
 * @author Comp11
 */
public class returnFRM extends javax.swing.JFrame {

    /** Creates new form returnFRM */
    public returnFRM() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        qtyTF = new javax.swing.JTextField();
        itemCB = new javax.swing.JComboBox();
        panel1 = new java.awt.Panel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Btn1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        Btn1.setText("Return");
        Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jButton2.setText("<html>Back To<br>Main Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jLabel4.setText("Name of Item");

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        jLabel5.setText("Qty. Returned");

        qtyTF.setEditable(false);
        qtyTF.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        qtyTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                qtyTFFocusLost(evt);
            }
        });
        qtyTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qtyTFKeyTyped(evt);
            }
        });

        itemCB.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        itemCB.setEnabled(false);
        itemCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCBActionPerformed(evt);
            }
        });
        itemCB.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                itemCBFocusGained(evt);
            }
        });

        panel1.setBackground(new java.awt.Color(153, 233, 153));
        panel1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images (6).jpg"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(0, 204, 255));
        jLabel1.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Return a Item to Physics Lab");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel4))
                    .addComponent(jLabel5))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(qtyTF)
                    .addComponent(itemCB, 0, 214, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel5))
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(itemCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(qtyTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1ActionPerformed
String str1 = (String)itemCB.getSelectedItem();
String str2=qtyTF.getText();
if(str2.length()==0){
JOptionPane.showMessageDialog(null,"Please write no. of Item returned!");
}
else if(!str2.matches("[0-9]*")){
JOptionPane.showMessageDialog(null,"Please type only numbers in Qty. field");
}
else if(str2.length()!=0|| str2.trim()!=null){
try{
                Class.forName("com.mysql.jdbc.Driver");
                System.out.print("\nConnecting to database...");
Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/kashyap", "root", "kvalwar");
System.out.println(" SUCCESS!\n");
Statement stmt = con.createStatement();
String query="UPDATE lab SET number=number+"+str2+" "+"WHERE ItemName= "+"'"+str1+"';";
stmt.executeUpdate(query);
query = "SELECT * FROM lab WHERE ItemName="+"'"+str1+"';";
ResultSet rs = stmt.executeQuery(query);
if ( rs.next()){
String price = rs.getString(3);
String life = rs.getString(4);
String  qty= rs.getString(5);
String dep = rs.getString(6);
String  date = rs.getString(7);
}
DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
Date date2 = new Date();
JOptionPane.showMessageDialog(null,"<html><b><u>Report</u></b><br><br>Item Returned Successfully.<br>Date:-"+date2);
rs.close();
stmt.close();
con.close();
}
catch(Exception e){
    JOptionPane.showMessageDialog(null,"Error in Connectivity!");
}
}       // TODO add your handling code here:
}//GEN-LAST:event_Btn1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        myFrame2 frame=new myFrame2();
        returnFRM.this.setVisible(false);
        frame.setVisible(true);       // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

    private void itemCBFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemCBFocusGained
        // TODO add your handling code here:
}//GEN-LAST:event_itemCBFocusGained

    private void itemCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCBActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_itemCBActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
try {
Class.forName("com.mysql.jdbc.Driver");
System.out.print("\nConnecting to database...");
Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/kashyap", "root", "kvalwar");
System.out.print("\nConnecting to database...");
Statement statement = connection.createStatement();
String query = "SELECT * FROM lab";
ResultSet rs = statement.executeQuery(query);
while (rs.next())
{
String name = rs.getString("ItemName");
itemCB.addItem(name);
}//end while
connection.close();
itemCB.setEnabled(true);
qtyTF.setEditable(true);
} catch (Exception e) {
e.printStackTrace();
}        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void qtyTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyTFKeyTyped
// TODO add your handling code here:
    }//GEN-LAST:event_qtyTFKeyTyped

    private void qtyTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qtyTFFocusLost
String a=qtyTF.getText();
if(!jButton2.getModel().isPressed()){
 if(!a.matches("[0-9]*")){
     JOptionPane.showMessageDialog(null,"Please type only numbers in qty. returned Field");
     qtyTF.setText("");
    }}        // TODO add your handling code here:
    }//GEN-LAST:event_qtyTFFocusLost

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new returnFRM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn1;
    private javax.swing.JComboBox itemCB;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private java.awt.Panel panel1;
    private javax.swing.JTextField qtyTF;
    // End of variables declaration//GEN-END:variables

}
